# This requires docker-compose 1.6.0 or later
version: '2'
services:
  rtpengine:
    privileged: true
    build:
      context: .
      dockerfile: Dockerfile.centos7
    network_mode: host
    environment:
      # Comment the variables that you don't want to be used for the configuration
      RUN_RTPENGINE: "yes"
      #LISTEN_TCP: 25060
      #LISTEN_UDP: 12222
      LISTEN_NG: 127.0.0.1:60000
      LISTEN_CLI: 127.0.0.1:60001
      # INTERFACES: "internal/12.23.34.45 external/23.34.45.54"
      # INTERFACES: "12.23.34.45!23.34.45.56"
      TIMEOUT: 60
      SILENT_TIMEOUT: 3600
      FORK: "no"
      # TOS: 184
      TABLE: 40
      NO_FALLBACK: "yes"
      PORT_MIN: 10000
      PORT_MAX: 19999
      # REDIS: 127.0.0.1:6379
      # REDIS_DB: 1
      # REDIS_READ: 127.0.0.1:6379
      # REDIS_READ_DB: 1
      # REDIS_WRITE: 127.0.0.1:6379
      # REDIS_WRITE_DB: 1
      # B2B_URL: http://127.0.0.1:8090/
      LOG_LEVEL: 6
      LOG_FACILITY: local1
      # LOG_FACILITY_CDR: daemon
      # LOG_FACILITY_RTCP: daemon
      # NUM_THREADS: 5
      # DELETE_DELAY: 30
      # GRAPHITE: 9006
      # GRAPHITE_INTERVAL: 60
      # GRAPHITE_PREFIX: myownprefix
      # MAX_SESSIONS: 5000
  
